const ANNET = 'ANNET';
const FULLMEKTIG = 'FULLMEKTIG';
const ARBEIDSGIVER = 'ARBEIDSGIVER';
const ARBEIDSGIVER_FULLMEKTIG = 'ARBEIDSGIVER_FULLMEKTIG';

export {
  ANNET,
  ARBEIDSGIVER,
  ARBEIDSGIVER_FULLMEKTIG,
  FULLMEKTIG,
};
