// DEPRECATED melosys.fullmakt.trygdeavgift
const FULLMEKTIG = "FULLMEKTIG";
// DEPRECATED melosys.fullmakt.trygdeavgift
const ARBEIDSGIVER = "ARBEIDSGIVER";
// DEPRECATED melosys.fullmakt.trygdeavgift
const ANNEN = "ANNEN";
const ANNEN_PERSON_ELLER_VIRKSOMHET = "ANNEN_PERSON_ELLER_VIRKSOMHET";
const FRITEKST = "FRITEKST";
const PERSON = "PERSON";

export { ARBEIDSGIVER, FULLMEKTIG, ANNEN, PERSON, FRITEKST, ANNEN_PERSON_ELLER_VIRKSOMHET };
