const ANNET = "ANNET";
const FULLMEKTIG = "FULLMEKTIG";
const VIRKSOMHET = "VIRKSOMHET";
const ARBEIDSGIVER = "ARBEIDSGIVER";
const ARBEIDSGIVER_FULLMEKTIG = "ARBEIDSGIVER_FULLMEKTIG";

export { ANNET, ARBEIDSGIVER, ARBEIDSGIVER_FULLMEKTIG, FULLMEKTIG, VIRKSOMHET };
