// Melosys-kodeverk
// Se Confluence koder for oversikt

export const INNVILGET = 'INNVILGET';
export const AVSLAATT = 'AVSLAATT';

// Interne frontend-spesifikke koder. Disse har ikke fag, brev eller arkitektur noe
// forhold til, og benyttes kun frontend for å avgjøre riktige steg pr ID.
export const SOKNADSLAND = 'SOKNADSLAND';
export const YRKESGRUPPE = 'YRKESGRUPPE';
export const YRKESAKTIVITET_ANTALL_LAND = 'YRKESAKTIVITET_ANTALL_LAND';
export const YRKESAKTIVITET = 'YRKESAKTIVITET';
export const AVKLARTE_ARBEIDSGIVER = 'AVKLARTE_ARBEIDSGIVER';
export const SOKKEL = 'SOKKEL';
export const SKIP = 'SKIP';
export const VurderingSokkelSkipTyper = {
  SKIP_NORSK_TERRITORIAL: 'SKIP_NORSK_TERRITORIAL',
  SKIP_ETT_LAND: 'SKIP_ETT_LAND',
  SOKKEL_NORSK: 'SOKKEL_NORSK',
  SOKKEL_UTLAND: 'SOKKEL_UTLAND',
  SOKKEL_ELLER_SKIP_FLERE_LAND: 'SOKKEL_ELLER_SKIP_FLERE_LAND',
};
export const VurderingForretningsstedTyper = {
  ID: 'FORRETNINGSSTED',
  EN_ARBEIDSGIVER: 'EN_ARBEIDSGIVER',
  TO_ELLER_FLERE_ARBEIDSGIVERE: 'TO_ELLER_FLERE_ARBEIDSGIVERE',
  SAMME_LAND: 'SAMME_LAND',
  ULIKE_LAND: 'ULIKE_LAND',
};
export const VurderingIkkeYrkesaktivTyper = {
  STUDENT: 'STUDENT',
  PENSJONIST: 'PENSJONIST',
  INGEN_AV_DISSE: 'INGEN_AV_DISSE',
};
export const VurderingTjenestemannTyper = {
  ID: 'OFFENTLIGTJENSTEMANN',
  ETT_LAND: 'ETT_LAND',
  ETT_LAND_YRKESAKTIVITET_ANDRE_LAND: 'ETT_LAND_YRKESAKTIVITET_ANDRE_LAND',
  FLERE_LAND: 'FLERE_LAND',
  FLERE_LAND_YRKESAKTIVITET_ANDRE_LAND: 'FLERE_LAND_YRKESAKTIVITET_ANDRE_LAND',
  IKKE_TJENESTEMANN: 'IKKE_TJENESTEMANN',
};
export const VurderingVirksomhetTyper = {
  EN_ELLER_BEGGE: 'EN_ELLER_BEGGE',
  INGEN_VEKSLING: 'INGEN_VEKSLING',
  MARGINALT_JA: 'MARGINALT_JA',
  MARGINALT_NEI: 'MARGINALT_NEI',
  UNDER_25_PROSENT: 'UNDER_25_PROSENT',
  OVER_25_PROSENT: 'OVER_25_PROSENT',
};
export const VurderingYrkesaktivitetTyper = {
  ID: 'YRKESAKTIVITET',
  ORDINAER_ARBEIDSTAKER: 'ORDINAER_ARBEIDSTAKER',
  SELVSTENDIG_NAERINGSDRIVENDE: 'SELVSTENDIG_NAERINGSDRIVENDE',
  ORDINAER_OG_SELVSTENDIG: 'ORDINAER_OG_SELVSTENDIG',
  TJENESTEPERSON_NORSK_STATSFORVANTLING: 'TJENESTEPERSON_NORSK_STATSFORVANTLING',
};
export const VurderingYrkesaktivitetAntallLandTyper = {
  ETT_LAND_IKKE_NORGE: 'ETT_LAND_IKKE_NORGE',
  KUN_NORGE: 'KUN_NORGE',
  TO_ELLER_FLERE_LAND: 'TO_ELLER_FLERE_LAND',
};
export const VurderingYrkesgruppeTyper = {
  ORDINAER: 'ORDINAER',
  SOKKEL_ELLER_SKIP: 'SOKKEL_ELLER_SKIP',
  FLYENDE_PERSONELL: 'YRKESAKTIV_FLYVENDE',
  IKKE_YRKESAKTIV: 'IKKE_YRKESAKTIV',
  KONTANTYTELSESMOTTAKER: 'KONTANTYTELSESMOTTAKER',
};

/* Dette er kodene for hver enkelt steg i stegvelgeren og avklartfakta eller vilkår. Fag eller arkitektur har ingen
 * spesielle krav eller forhold til disse kodene, men noen kan sammenfalle med koder som fag bruker.
 */
export const avklartefaktaKoder = {
  SOKNADSLAND: 'SOKNADSLAND',
  YRKESGRUPPE: 'YRKESGRUPPE',
  YRKESAKTIVITET_ANTALL_LAND: 'YRKESAKTIVITET_ANTALL_LAND',
  YRKESAKTIVITET: 'YRKESAKTIVITET',
  AKTIVITET_I_NORGE: 'AKTIVITET_I_NORGE',
  VIRKSOMHET: 'VIRKSOMHET',
  MARGINALT_ARBEID: 'MARGINALT_ARBEID',
  SOKKEL_ELLER_SKIP: 'SOKKEL_ELLER_SKIP',
  ARBEIDSLAND: 'ARBEIDSLAND',
  BOSTEDSLAND: 'BOSTEDSLAND',
  ARBEID_SOKKEL_SKIP: 'ARBEID_SOKKEL_SKIP',
};
export const referanseKoder = {
  INSTALLASJON_ARBEIDSLAND: 'INSTALLASJON_ARBEIDSLAND',
  INSTALLASJON_ARBEIDSLAND_TYPE: 'INSTALLASJON_ARBEIDSLAND_TYPE',
};
