// Melosys-kodeverk
// Se Confluence koder for oversikt

export const INNVILGET = 'INNVILGET';
export const DELVIS_INNVILGET = 'DELVIS_INNVILGET';
export const AVSLAATT = 'AVSLAATT';

// Interne frontend-spesifikke koder. Disse har ikke fag, brev eller arkitektur noe
// forhold til, og benyttes kun frontend for å avgjøre riktige steg pr ID.
export const SOKNADSLAND = 'SOKNADSLAND';
export const YRKESGRUPPE = 'YRKESGRUPPE';
export const YRKESAKTIVITET = 'YRKESAKTIVITET';
export const AVKLARTE_ARBEIDSGIVER = 'AVKLARTE_ARBEIDSGIVER';
export const SOKKEL = 'SOKKEL';
export const SKIP = 'SKIP';

export const Unntaksperiode = {
  GODKJENT: 'GODKJENT',
  DELVIS_GODKJENT: 'DELVIS_GODKJENT',
  AVSLAG: 'AVSLAG',
};
export const VurderingSokkelSkipTyper = {
  SKIP_NORSK_TERRITORIAL: 'SKIP_NORSK_TERRITORIAL',
  SKIP_ETT_LAND: 'SKIP_ETT_LAND',
  SOKKEL_NORSK: 'SOKKEL_NORSK',
  SOKKEL_UTLAND: 'SOKKEL_UTLAND',
  SOKKEL_ELLER_SKIP_FLERE_LAND: 'SOKKEL_ELLER_SKIP_FLERE_LAND',
};
export const VurderingForretningsstedTyper = {
  ID: 'FORRETNINGSSTED',
  EN_ARBEIDSGIVER: 'EN_ARBEIDSGIVER',
  TO_ELLER_FLERE_ARBEIDSGIVERE: 'TO_ELLER_FLERE_ARBEIDSGIVERE',
  SAMME_LAND: 'SAMME_LAND',
  ULIKE_LAND: 'ULIKE_LAND',
};
export const VurderingIkkeYrkesaktivTyper = {
  STUDENT: 'STUDENT',
  PENSJONIST: 'PENSJONIST',
  INGEN_AV_DISSE: 'INGEN_AV_DISSE',
};
export const VurderingTjenestemannTyper = {
  ID: 'OFFENTLIGTJENSTEMANN',
  ETT_LAND: 'ETT_LAND',
  ETT_LAND_YRKESAKTIVITET_ANDRE_LAND: 'ETT_LAND_YRKESAKTIVITET_ANDRE_LAND',
  FLERE_LAND: 'FLERE_LAND',
  FLERE_LAND_YRKESAKTIVITET_ANDRE_LAND: 'FLERE_LAND_YRKESAKTIVITET_ANDRE_LAND',
  IKKE_TJENESTEMANN: 'IKKE_TJENESTEMANN',
};

export const VurderingYrkesaktivitetTyper = {
  ID: 'YRKESAKTIVITET',
  ORDINAER_ARBEIDSTAKER: 'ORDINAER_ARBEIDSTAKER',
  SELVSTENDIG_NAERINGSDRIVENDE: 'SELVSTENDIG_NAERINGSDRIVENDE',
  ORDINAER_OG_SELVSTENDIG: 'ORDINAER_OG_SELVSTENDIG',
  TJENESTEPERSON_NORSK_STATSFORVANTLING: 'TJENESTEPERSON_NORSK_STATSFORVANTLING',
};
export const VurderingYrkesaktivitetAntallLandTyper = {
  ETT_LAND_IKKE_NORGE: 'ETT_LAND_IKKE_NORGE',
  KUN_NORGE: 'KUN_NORGE',
  TO_ELLER_FLERE_LAND: 'TO_ELLER_FLERE_LAND',
};
export const VurderingYrkesgruppeTyper = {
  ORDINAER: 'ORDINAER',
  SOKKEL_ELLER_SKIP: 'SOKKEL_ELLER_SKIP',
  FLYENDE_PERSONELL: 'YRKESAKTIV_FLYVENDE',
  IKKE_YRKESAKTIV: 'IKKE_YRKESAKTIV',
  KONTANTYTELSESMOTTAKER: 'KONTANTYTELSESMOTTAKER',
  ORDINAER_UTEN_ART12: 'ORDINAER_UTEN_ART12',
};

export const VurderingSkiftesvisSekvensieltArbeid = {
  SKIFTESVIS: 'SKIFTESVIS',
  SEKVENSIELT: 'SEKVENSIELT',
};

export const VurderingVesentligAktivitetINorgeTyper = {
  UNDER_25_PROSENT: 'UNDER_25_PROSENT',
  OVER_25_PROSENT: 'OVER_25_PROSENT',
};

export const BoolskAvklartfaktaType = {
  SANN: 'TRUE',
  USANN: 'FALSE',
};

export const AdresseType = {
  STRUKTURERT: 'STRUKTURERT',
  USTRUKTURERT: 'USTRUKTURERT',
};

export const SedStatus = {
  UTKAST: 'UTKAST',
  SENDT: 'SENDT',
  MOTTATT: 'MOTTATT',
  TOM: 'TOM',
  AVBRUTT: 'AVBRUTT',
};

/* Dette er kodene for hver enkelt steg i stegvelgeren og avklartfakta eller vilkår. Fag eller arkitektur har ingen
 * spesielle krav eller forhold til disse kodene, men noen kan sammenfalle med koder som fag bruker.
 */
export const avklartefaktaKoder = {
  AKTIVITET_I_NORGE: 'AKTIVITET_I_NORGE',
  ARBEIDSLAND: 'ARBEIDSLAND',
  ARBEIDSMONSTER: 'ARBEIDSMONSTER',
  ARBEID_SOKKEL_SKIP: 'ARBEID_SOKKEL_SKIP',
  ARBEIDSGIVERS_FORRETNINGSSTED: 'ARBEIDSGIVERS_FORRETNINGSSTED',
  BOSTEDSLAND: 'BOSTEDSLAND',
  MARGINALT_ARBEID: 'MARGINALT_ARBEID',
  OMFATTES_I_NORGE: 'OMFATTES_I_NORGE',
  OMFATTES_I_LAND: 'OMFATTES_I_LAND',
  SOKKEL_ELLER_SKIP: 'SOKKEL_ELLER_SKIP',
  SOKNADSLAND: 'SOKNADSLAND',
  VIRKSOMHET: 'VIRKSOMHET',
  VURDERING_UNNTAK_PERIODE: 'VURDERING_UNNTAK_PERIODE',
  YRKESAKTIVITET: 'YRKESAKTIVITET',
  YRKESGRUPPE: 'YRKESGRUPPE',
  UTPEKING_GODKJENT: 'UTPEKING_GODKJENT',
  ARBEID_UTFORES_I_OPPGITT_LAND: 'ARBEID_UTFORES_I_OPPGITT_LAND',
};
export const referanseKoder = {
  INSTALLASJON_ARBEIDSLAND: 'INSTALLASJON_ARBEIDSLAND',
  INSTALLASJON_ARBEIDSLAND_TYPE: 'INSTALLASJON_ARBEIDSLAND_TYPE',
};

export const Tema = {
  MED: 'Medlemskap',
  UFM: 'Unntak fra medlemskap',
};

export const UtpekingAvNorgeGodkjenning = {
  GODKJENN: 'GODKJENN',
  IKKE_GODKJENN: 'IKKE_GODKJENN',
};
