// Interne frontend-spesifikke koder. Disse har ikke fag, brev eller arkitektur noe
// forhold til, og benyttes kun frontend for å avgjøre riktige steg pr ID.
export const YRKESGRUPPE = "YRKESGRUPPE";
export const YRKESAKTIVITET = "YRKESAKTIVITET";
export const SOKKEL = "SOKKEL";
export const SKIP = "SKIP";

export const Unntaksperiode = {
  GODKJENT: "GODKJENT",
  DELVIS_GODKJENT: "DELVIS_GODKJENT",
  AVSLAG: "AVSLAG",
};

export const VurderingSokkelSkipTyper = {
  SKIP_NORSK_TERRITORIAL: "SKIP_NORSK_TERRITORIAL",
  SKIP_ETT_LAND: "SKIP_ETT_LAND",
  SOKKEL_NORSK: "SOKKEL_NORSK",
  SOKKEL_UTLAND: "SOKKEL_UTLAND",
  SOKKEL_ELLER_SKIP_FLERE_LAND: "SOKKEL_ELLER_SKIP_FLERE_LAND",
};

export const VurderingYrkesaktivitetTyper = {
  ID: "YRKESAKTIVITET",
  ORDINAER_ARBEIDSTAKER: "ORDINAER_ARBEIDSTAKER",
  SELVSTENDIG_NAERINGSDRIVENDE: "SELVSTENDIG_NAERINGSDRIVENDE",
  ORDINAER_OG_SELVSTENDIG: "ORDINAER_OG_SELVSTENDIG",
  TJENESTEPERSON_NORSK_STATSFORVANTLING: "TJENESTEPERSON_NORSK_STATSFORVANTLING",
};

export const VurderingYrkesgruppeTyper = {
  ORDINAER: "ORDINAER",
  SOKKEL_ELLER_SKIP: "SOKKEL_ELLER_SKIP",
  FLYENDE_PERSONELL: "YRKESAKTIV_FLYVENDE",
  IKKE_YRKESAKTIV: "IKKE_YRKESAKTIV",
  KONTANTYTELSESMOTTAKER: "KONTANTYTELSESMOTTAKER",
  ORDINAER_UTEN_ART12: "ORDINAER_UTEN_ART12",
};

export const VurderingVesentligAktivitetINorgeTyper = {
  UNDER_25_PROSENT: "UNDER_25_PROSENT",
  OVER_25_PROSENT: "OVER_25_PROSENT",
};

export const SoknadslandFaktaTyper = {
  IKKE_ARBEIDSLAND: "IKKE_ARBEIDSLAND",
};

export const SedStatus = {
  UTKAST: "UTKAST",
  SENDT: "SENDT",
  MOTTATT: "MOTTATT",
  TOM: "TOM",
  AVBRUTT: "AVBRUTT",
};

export const AlertstripeTekst = {
  NY_VURDERING_MEDL_TEKST: "Ny periode erstatter eksisterende periode i MEDL",
};

/* Dette er kodene for hver enkelt steg i stegvelgeren og avklartfakta eller vilkår. Fag eller arkitektur har ingen
 * spesielle krav eller forhold til disse kodene, men noen kan sammenfalle med koder som fag bruker.
 */
export const avklartefaktaKoder = {
  AKTIVITET_I_NORGE: "AKTIVITET_I_NORGE",
  ARBEIDSLAND: "ARBEIDSLAND",
  ARBEIDSMONSTER: "ARBEIDSMONSTER",
  ARBEID_SOKKEL_SKIP: "ARBEID_SOKKEL_SKIP",
  ARBEIDSGIVERS_FORRETNINGSSTED: "ARBEIDSGIVERS_FORRETNINGSSTED",
  BOSTEDSLAND: "BOSTEDSLAND",
  OMFATTES_I_NORGE: "OMFATTES_I_NORGE",
  OMFATTES_I_LAND: "OMFATTES_I_LAND",
  SOKKEL_ELLER_SKIP: "SOKKEL_ELLER_SKIP",
  SOKNADSLAND: "SOKNADSLAND",
  VIRKSOMHET: "VIRKSOMHET",
  VURDERING_UNNTAK_PERIODE: "VURDERING_UNNTAK_PERIODE",
  YRKESAKTIVITET: "YRKESAKTIVITET",
  YRKESGRUPPE: "YRKESGRUPPE",
  ARBEID_UTFORES_I_OPPGITT_LAND: "ARBEID_UTFORES_I_OPPGITT_LAND",
  LOENNET_ARBEID_ANTALL_LAND: "LOENNET_ARBEID_ANTALL_LAND",
  OFFENTLIG_ARBEID_ANTALL_LAND: "OFFENTLIG_ARBEID_ANTALL_LAND",
  UKJENT_SLUTTDATO: "UKJENT_SLUTTDATO",
};
export const referanseKoder = {
  INSTALLASJON_ARBEIDSLAND: "INSTALLASJON_ARBEIDSLAND",
  INSTALLASJON_ARBEIDSLAND_TYPE: "INSTALLASJON_ARBEIDSLAND_TYPE",
};

export const Tema = {
  MED: "Medlemskap",
  UFM: "Unntak fra medlemskap",
  TRY: "Trygdeavgift",
};

export const LoennetArbeidAntallLand = {
  NORGE: "NORGE",
  ETT_ANNET_LAND: "ETT_ANNET_LAND",
  FLERE_LAND: "FLERE_LAND",
};

export const OffentligArbeidAntallLand = {
  NORGE_OG_ANNEN_VIRKSOMHET: "NORGE_OG_ANNEN_VIRKSOMHET",
  ANNET_LAND_OG_ANNEN_VIRKSOMHET: "ANNET_LAND_OG_ANNEN_VIRKSOMHET",
  FLERE_LAND_OG_ANNEN_VIRKSOMHET: "FLERE_LAND_OG_ANNEN_VIRKSOMHET",
};

export const Opplysningskilder = {
  TPS: "TPS",
  MEDL: "MEDL",
  UTBETAL: "Utbetalingstjenesten",
  AAREG_EREG: "Aa-registeret og Enhetsregisteret",
  INNTEKT: "Inntektskomponenten",
};

export const Relasjonsrolle = {
  BARN: "BARN",
  EKTEFELLE_SAMBOER: "EKTEFELLE_SAMBOER",
  EKTE: "EKTE",
  REPA: "REPA",
  SAMB: "SAMB",
};

export enum StegNavn {
  INNGANG = "INNGANG",
  AVKLAR_VIRKSOMHET = "AVKLAR_VIRKSOMHET",
  BESTEMMELSE = "BESTEMMELSE",
  FAMILIE = "FAMILIE",
  VEDTAK = "VEDTAK",
}

export const FRITEKST_VALG = "Fritekst";

export enum AVTALELAND_UTFALL {
  JA_FATTE_VEDTAK = "JA_FATTE_VEDTAK",
  NEI_ANMODE_OM_UNNTAK = "NEI_ANMODE_OM_UNNTAK",
  NEI_AVSLAG = "NEI_AVSLAG",
}
