export const foretakUtland = 'Arbeidsgiver i utlandet';
export const arbeidUtland = 'Opplysninger om fysisk arbeidssted i utlandet';
export const soknadsPeriode = 'Søknadsperiode';
export const selvstendigNaeringsdrivende = 'Arbeid som selvstendig næringsdrivende';
export const fullmektig = 'Fullmektig';
export const arbeidsgiversVirksomhetINorge = 'Opplysninger om arbeidsgivers virksomhet i Norge';
export const maritimtArbeid = 'Maritimt Arbeid';
export const medlemskap = 'Medlemskap';
export const inntektUnderOpphold = 'Inntekt under oppholdet';
export const arbeidsgiverINorge = navn => `Arbeidsgiver i Norge: ${navn}`;
export const kontantytelser = 'Kontantytelser fra NAV';
