export const OPPDATER_HENLEGG = "modaler/OPPDATER_HENLEGG";
export const OPPDATER_AVSLAG_SOKNAD = "modaler/OPPDATER_AVSLAG_SOKNAD";
export const OPPDATER_OPPFRISK = "modaler/OPPDATER_OPPFRISK";
export const OPPDATER_BEKREFT_VALG = "modaler/OPPDATER_FERDIGBEHANDLE_SAK";
