# Listene må ha samme felter som hentPersoninfo og hentStatsborgerskap for å unngå cachetap.
query hentPersonopplysninger($behandlingID: Long!) {
  hentSaksopplysninger(behandlingID: $behandlingID) {
    persondata {
      navn {
        fornavn
        mellomnavn
        etternavn
      }
      kjoenn
      folkeregisterpersonstatuser {
        kode
        tekst
        master
        kilde
        fregGyldighetstidspunkt
        erHistorisk
      }
      folkeregisteridentifikator
      statsborgerskap {
        land
        bekreftelsesdato
        gyldigFraOgMed
        gyldigTilOgMed
        master
        kilde
        erHistorisk
      }
      sivilstand {
        type
        relatertVedSivilstand
        gyldigFraOgMed
        bekreftelsesdato
        master
        kilde
        erHistorisk
      }
    }
  }
}
