/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type * as Types from '../../graphql/generated/types';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type KjoennType =
  | 'KVINNE'
  | 'MANN'
  | 'UKJENT';

export type HentPersonopplysningerQueryVariables = Exact<{
  behandlingID: number;
}>;


export type HentPersonopplysningerQuery = { hentSaksopplysninger: { persondata: { kjoenn: Types.KjoennType, folkeregisteridentifikator: string | null, navn: { fornavn: string, mellomnavn: string | null, etternavn: string }, folkeregisterpersonstatuser: Array<{ kode: string, tekst: string, master: string, kilde: string | null, fregGyldighetstidspunkt: string | null, erHistorisk: boolean }>, statsborgerskap: Array<{ land: string, bekreftelsesdato: string | null, gyldigFraOgMed: string | null, gyldigTilOgMed: string | null, master: string, kilde: string | null, erHistorisk: boolean }>, sivilstand: Array<{ type: string, relatertVedSivilstand: string | null, gyldigFraOgMed: string | null, bekreftelsesdato: string | null, master: string, kilde: string | null, erHistorisk: boolean }> } } };


export const HentPersonopplysningerDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"hentPersonopplysninger"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"behandlingID"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Long"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hentSaksopplysninger"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"behandlingID"},"value":{"kind":"Variable","name":{"kind":"Name","value":"behandlingID"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"persondata"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"navn"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"fornavn"}},{"kind":"Field","name":{"kind":"Name","value":"mellomnavn"}},{"kind":"Field","name":{"kind":"Name","value":"etternavn"}}]}},{"kind":"Field","name":{"kind":"Name","value":"kjoenn"}},{"kind":"Field","name":{"kind":"Name","value":"folkeregisterpersonstatuser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"kode"}},{"kind":"Field","name":{"kind":"Name","value":"tekst"}},{"kind":"Field","name":{"kind":"Name","value":"master"}},{"kind":"Field","name":{"kind":"Name","value":"kilde"}},{"kind":"Field","name":{"kind":"Name","value":"fregGyldighetstidspunkt"}},{"kind":"Field","name":{"kind":"Name","value":"erHistorisk"}}]}},{"kind":"Field","name":{"kind":"Name","value":"folkeregisteridentifikator"}},{"kind":"Field","name":{"kind":"Name","value":"statsborgerskap"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"land"}},{"kind":"Field","name":{"kind":"Name","value":"bekreftelsesdato"}},{"kind":"Field","name":{"kind":"Name","value":"gyldigFraOgMed"}},{"kind":"Field","name":{"kind":"Name","value":"gyldigTilOgMed"}},{"kind":"Field","name":{"kind":"Name","value":"master"}},{"kind":"Field","name":{"kind":"Name","value":"kilde"}},{"kind":"Field","name":{"kind":"Name","value":"erHistorisk"}}]}},{"kind":"Field","name":{"kind":"Name","value":"sivilstand"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"relatertVedSivilstand"}},{"kind":"Field","name":{"kind":"Name","value":"gyldigFraOgMed"}},{"kind":"Field","name":{"kind":"Name","value":"bekreftelsesdato"}},{"kind":"Field","name":{"kind":"Name","value":"master"}},{"kind":"Field","name":{"kind":"Name","value":"kilde"}},{"kind":"Field","name":{"kind":"Name","value":"erHistorisk"}}]}}]}}]}}]}}]} as unknown as DocumentNode<HentPersonopplysningerQuery, HentPersonopplysningerQueryVariables>;