const MELOSYS_FAKTURERINGSKOMPONENTEN_VIS_REFERANSE = "melosys.faktureringskomponent.vis_referanse";
const MELOSYS_FTRL_IKKE_YRKESAKTIV = "melosys.ftrl.ikke_yrkesaktiv";
const MELOSYS_FTRL_BEGRENSE_PERIODE_VEDTAK = "melosys.ftrl.begrense_periode_vedtak";
const FEATURE_TOGGLE = "feature-toggle";
const MELOSYS_FTRL_YRKESAKTIV_PLIKTIGE_BESTEMMELSER = "melosys.ftrl.yrkesaktiv.pliktige_bestemmelser";
const MELOSYS_KONVENSJON_EFTA_LAND_OG_STORBRITANNIA = "melosys.konvensjon.efta.land.og.storbritannia";

const alleToggleNavn = [
  MELOSYS_FAKTURERINGSKOMPONENTEN_VIS_REFERANSE,
  MELOSYS_FTRL_BEGRENSE_PERIODE_VEDTAK,
  MELOSYS_FTRL_IKKE_YRKESAKTIV,
  MELOSYS_FTRL_YRKESAKTIV_PLIKTIGE_BESTEMMELSER,
  MELOSYS_KONVENSJON_EFTA_LAND_OG_STORBRITANNIA,
];

export {
  FEATURE_TOGGLE,
  MELOSYS_FAKTURERINGSKOMPONENTEN_VIS_REFERANSE,
  MELOSYS_FTRL_BEGRENSE_PERIODE_VEDTAK,
  MELOSYS_FTRL_IKKE_YRKESAKTIV,
  MELOSYS_FTRL_YRKESAKTIV_PLIKTIGE_BESTEMMELSER,
  MELOSYS_KONVENSJON_EFTA_LAND_OG_STORBRITANNIA,
  alleToggleNavn,
};
