const MELOSYS_FAKTURERINGSKOMPONENTEN_VIS_REFERANSE = "melosys.faktureringskomponent.vis_referanse";
const MELOSYS_FTRL_BEGRENSE_PERIODE_VEDTAK = "melosys.ftrl.begrense_periode_vedtak";
const FEATURE_TOGGLE = "feature-toggle";
const MELOSYS_NORGE_ER_UTPEKT_11_3_A = "melosys.11_3_a_Norge_er_utpekt";
const MELOSYS_PENSJONIST = "melosys.pensjonist";
const MELOSYS_PENSJONIST_EØS = "melosys.pensjonist_eos";
const STANDARDVEDLEGG_EGET_VEDLEGG_AVTALELAND = "standardvedlegg_eget_vedlegg_avtaleland";
const ÅRSAVREGNING = "melosys.arsavregning";
const ÅRSAVREGNING_UTEN_FLYT = "melosys.arsavregning.uten.flyt";
const ÅRSAVREGNING_EØS_PENSJONIST = "melosys.arsavregning.eos_pensjonist";
const ÅRSAVREGNING_EØS_TJENESTEPERSON = "melosys.arsavregning.eos_tjenesteperson";
const MELOSYS_FAKTURERINGSKOMPONENTEN_IKKE_TIDLIGERE_PERIODER =
  "melosys.faktureringskomponenten.ikke-tidligere-perioder";
const MELOSYS_EØS_FAKTURERING_AV_TRYGDEAVGIFT = "melosys.eos_fakturering_av_trygdeavgift";
const MELOSYS_CDM_4_4 = "melosys.cdm-4-4";
const MELOSYS_TEKSTBLOKKER = "melosys.tekstblokker";
const MELOSYS_ADMINISTRASJON = "melosys.administrasjon";
const MELOSYS_VIS_PENSJONSOPPTJENING_POPP = "melosys.vis-pensjonsopptjening-popp";

const alleToggleNavn = [
  MELOSYS_FTRL_BEGRENSE_PERIODE_VEDTAK,
  MELOSYS_NORGE_ER_UTPEKT_11_3_A,
  MELOSYS_PENSJONIST,
  MELOSYS_PENSJONIST_EØS,
  STANDARDVEDLEGG_EGET_VEDLEGG_AVTALELAND,
  ÅRSAVREGNING,
  ÅRSAVREGNING_UTEN_FLYT,
  ÅRSAVREGNING_EØS_PENSJONIST,
  ÅRSAVREGNING_EØS_TJENESTEPERSON,
  MELOSYS_FAKTURERINGSKOMPONENTEN_IKKE_TIDLIGERE_PERIODER,
  MELOSYS_EØS_FAKTURERING_AV_TRYGDEAVGIFT,
  MELOSYS_FAKTURERINGSKOMPONENTEN_VIS_REFERANSE,
  MELOSYS_CDM_4_4,
  MELOSYS_TEKSTBLOKKER,
  MELOSYS_ADMINISTRASJON,
  MELOSYS_VIS_PENSJONSOPPTJENING_POPP,
];

export {
  FEATURE_TOGGLE,
  MELOSYS_FTRL_BEGRENSE_PERIODE_VEDTAK,
  MELOSYS_NORGE_ER_UTPEKT_11_3_A,
  MELOSYS_PENSJONIST,
  MELOSYS_PENSJONIST_EØS,
  ÅRSAVREGNING,
  ÅRSAVREGNING_UTEN_FLYT,
  ÅRSAVREGNING_EØS_PENSJONIST,
  ÅRSAVREGNING_EØS_TJENESTEPERSON,
  STANDARDVEDLEGG_EGET_VEDLEGG_AVTALELAND,
  MELOSYS_FAKTURERINGSKOMPONENTEN_IKKE_TIDLIGERE_PERIODER,
  MELOSYS_EØS_FAKTURERING_AV_TRYGDEAVGIFT,
  MELOSYS_FAKTURERINGSKOMPONENTEN_VIS_REFERANSE,
  MELOSYS_CDM_4_4,
  MELOSYS_TEKSTBLOKKER,
  MELOSYS_ADMINISTRASJON,
  MELOSYS_VIS_PENSJONSOPPTJENING_POPP,
  alleToggleNavn,
};
