query hentPersoninfo($behandlingID: Long!) {
  hentSaksopplysninger(behandlingID: $behandlingID) {
    persondata {
      folkeregisterpersonstatuser {
        kode
        tekst
        master
        kilde
        fregGyldighetstidspunkt
        erHistorisk
      }
      foedested: {
        foedested
        foedeland
      }
      foedselsdato {
        foedselsaar
        foedselsdato
      }
      sivilstand {
        type
        relatertVedSivilstand
        gyldigFraOgMed
        bekreftelsesdato
        master
        kilde
        erHistorisk
      }
    }
  }
}
