/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 *
 * Dette er en "legacy" versjon av Steg-klassen for eksisterende .js-filer.
 *
 * HVIS DU TRENGER Å ENDRE STEG-LOGIKK:
 * 1. Konverter .js-filen som importerer denne til .ts
 * 2. Bytt import til './steg' (TypeScript-versjonen)
 * 3. Gjør endringen i steg.ts
 *
 * Mål: Når alle .js-filer er konvertert til .ts, kan denne filen slettes.
 *
 */

import * as Utils from "../../../utils";
import { FANE_STATUS, STEG } from "./typer";

class Steg {
  _id = null;
  _tittel = null;
  _kriterier = null;
  _komponent = null;
  _status = null;
  _samleRelevanteData = null;
  _beregnRelevantUI = null;
  _handlers = null;
  constructor(propsLight, posisjon) {
    this._propsLight = propsLight;
    this._stegPosisjon = posisjon;
  }

  get id() {
    return this._id;
  }
  set id(id) {
    this._id = id;
  }
  get tittel() {
    return this._tittel;
  }
  set tittel(tittel) {
    this._tittel = tittel;
  }
  get komponent() {
    return this._komponent;
  }
  set komponent(komponent) {
    this._komponent = komponent;
  }
  get kriterier() {
    return this._kriterier;
  }
  set kriterier(kriterier) {
    this._kriterier = kriterier;
  }
  get handlers() {
    return this._handlers;
  }
  set handlers(handlers) {
    this._handlers = handlers;
  }
  get status() {
    return this._status;
  }
  set status(status) {
    this._status = status;
  }
  set aktivtSteg(aktiv) {
    this._aktiv = aktiv;
  }
  get samleRelevanteData() {
    return this._samleRelevanteData;
  }
  set samleRelevanteData(samleRelevanteData) {
    this._samleRelevanteData = samleRelevanteData;
  }
  get beregnRelevantUI() {
    return this._beregnRelevantUI;
  }
  set beregnRelevantUI(beregnRelevantUI) {
    this._beregnRelevantUI = beregnRelevantUI;
  }

  byggSteg = () => ({
    id: this._id,
    komponent: this._komponent,
    tittel: this._tittel,
    handlers: this._handlers, // handlers + data -> propsLight
    data: { ...this._samleRelevanteData(this._propsLight), tilstand: this._beregnRelevantUI(this._propsLight) },
    status: this.hentStatus(),
    stegPosisjon: this._stegPosisjon,
    aktivtSteg: this._aktiv,
    vedtakSteg: this.erVedtakSteg(this._id),
  });

  nesteSteg = () => {
    const { avklartefakta = [], vilkar = [] } = this._propsLight;

    const kriterieMatch = this._kriterier.find((kriterie) => {
      const { exec } = kriterie;
      return this.assertRegel(exec, avklartefakta, vilkar);
    });

    return kriterieMatch && kriterieMatch.nesteSteg;
  };

  hentStatus = () => {
    const relevantUI = this.beregnRelevantUI(this._propsLight);
    if (!relevantUI) {
      return FANE_STATUS.FEIL;
    }
    return relevantUI.harAvklaring ? FANE_STATUS.OK : FANE_STATUS.UBEHANDLET;
  };

  erVedtakSteg = (id) =>
    id === STEG.VEDTAK ||
    id === STEG.ENDRET_PERIODE ||
    id === STEG.AVSLAG_12_X_OG_16 ||
    id === STEG.ARTIKKEL_16_VEDTAK ||
    id === STEG.ARTIKKEL_13_1_A_VEDTAK ||
    id === STEG.VIDERESEND ||
    id === STEG.ARTIKKEL_13_1_B_VEDTAK ||
    id === STEG.ARTIKKEL_13_1_B_UTPEK_LAND ||
    id === STEG.ARTIKKEL_13_2_A_VEDTAK ||
    id === STEG.GODKJENN_UTPEKING_NORGE ||
    id === STEG.GODKJENN_UTPEKING_ANNET_LAND ||
    id === STEG.AVSLAA_UTPEKING ||
    id === STEG.ARTIKKEL_13_2_B_UTPEK_LAND ||
    id === STEG.ARTIKKEL_13_3_VEDTAK ||
    id === STEG.ARTIKKEL_13_3_UTPEK_LAND ||
    id === STEG.ARTIKKEL_13_4_VEDTAK ||
    id === STEG.ARTIKKEL_13_4_UTPEK_LAND ||
    id === STEG.ARBEID_TJENESTEPERSON_ELLER_FLY_VEDTAK;

  assertRegel = (regel, avklartefakta, vilkar) => (Utils._isFunction(regel) ? regel(avklartefakta, vilkar) : false);
}

export default Steg;
