export const OK = 'sed/OK';
export const FEILET = 'sed/FEILET';
export const PENDING = 'sed/PENDING';
export const RESET = 'sed/RESET';
export const OPPDATER_SEDUNDERARBEID = 'sed/OPPDATER_SEDUNDERARBEID';
export const OPPDATER_BUCSEDRELASJONER = 'sed/OPPDATER_BUCSEDRELASJONER';
export const OPPDATER_MOTTAKERINSTITUSJONER = 'sed/OPPDATER_MOTTAKERINSTITUSJONER';
