apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{APP_NAME}}
  namespace: teammelosys
  labels:
    team: teammelosys
  annotations:
    nais.io/security-does-not-matter: "true"
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: melosys/health/is-alive
    initialDelay: 30
    timeout: 10
  readiness:
    path: melosys/health/is-ready
    initialDelay: 30
    timeout: 10
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: true
  ingresses:
    - {{INGRESS}}
  env:
    - name: REDIS_HOST
      value: {{REDIS_APP_NAME}}.teammelosys.svc.nais.local
    - name: APP_URL_MELOSYS
      value: {{APP_URL_MELOSYS}}
    - name: APP_URL_TRYGDEAVTALE
      value: {{APP_URL_TRYGDEAVTALE}}
