query hentFamiliemedlemmer($behandlingID: Long!) {
  hentSaksopplysninger(behandlingID: $behandlingID) {
    persondata {
      familiemedlemmer {
        navn
        ident
        relasjonsrolle
        alder
        foreldreansvar
        fnrAnnenForelder
        sivilstand {
          type
          gyldigFraOgMed
          erHistorisk
        }
      }
    }
  }
}
