/* eslint-disable */
/** Hver fane kan ha en rekke forskjellige statuser som er ment å indikere
 * feil eller varsler som saksbehandleren må håndtere.
 *
 * @type {{UBEHANDLET: string, AKTIV: string, BEHANDLET: string, ADVARSEL: string, FEIL: string}}
 */
export const FANE_STATUS = {
  UBEHANDLET: 'UBEHANDLET',
  AKTIV: 'AKTIV',
  OK: 'OK',
  ADVARSEL: 'ADVARSEL',
  FEIL: 'FEIL',
};

export const STEG = {
  ARTIKKEL_16: 'ARTIKKEL_16',
  ARTIKKEL_12: 'ARTIKKEL_12',
  INNGANG: 'INNGANG',
  SYSSELSETTING: 'SYSSELSETTING',
  IKKE_YRKESAKTIV: 'IKKE_YRKESAKTIV',
  FORUTGAENDE_MEDLEMSKAP: 'FORUTGAENDE_MEDLEMSKAP',
  YRKESAKTIVITET: 'YRKESAKTIVITET',
  UTSENDING: 'UTSENDING',
  YRKESAKTIVITET_ANTALL_LAND: 'YRKESAKTIVITET_ANTALL_LAND',
  VIRKSOMHET: 'VIRKSOMHET',
  VESENTLIG_VIRKSOMHET: 'VESENTLIG_VIRKSOMHET',
  AKTIVITET: 'AKTIVITET',
  BOSTEDSLAND: 'BOSTEDSLAND',
  TJENESTEMANN: 'TJENESTEMANN',
  FORRETNINGSSTED: 'FORRETNINGSSTED',
  ARBEIDSGIVERE: 'ARBEIDSGIVERE',
  VEDTAK: 'VEDTAK',
};
