query hentPersonopplysninger($behandlingID: Long!, $historikk: Boolean) {
  hentSaksopplysninger(behandlingID: $behandlingID) {
    persondata {
      navn(historikk: $historikk) {
        fornavn
        mellomnavn
        etternavn
      }
      kjoenn
      folkeregisterpersonstatuser {
        kode
        erHistorisk
      }
      folkeregisteridentifikator
      statsborgerskap {
        land
        erHistorisk
      }
      sivilstand {
        type
        erHistorisk
      }
    }
  }
}
