export const JOURNALFORING_HENSIKT = {
  KNYTT: "KNYTT",
  ANDREGANGSBEHANDLE: "ANDREGANGSBEHANDLE",
  OPPRETT: "OPPRETT",
};

export const BOOLSK_STRING = {
  SANN: "TRUE",
  USANN: "FALSE",
};

export const URL_BASENAME = process.env.APP_PATH_PREFIX || "/melosys";
