name: deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - master
permissions:
    contents: write
    packages: write
    id-token: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest-8-cores
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
      telemetry: ${{ steps.docker-push.outputs.telemetry }}
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '22.11.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
      - name: install dependencies
        env:
          # NPM krever tydeligvis en token for å hente pakker fra github packages
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm ci
      - name: check formatting
        run: npm run prettier:check
      - name: build css
        run: npm run build:css
      - name: lint
        run: npm run eslint
      - name: test
        run: npm run test
        env:
          CI: true
      - name: build
        run: |
          BRANCH_NAME=$GITHUB_REF
          BUILD_NUMBER="$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)"
          npm run build
      - name: Build and publish Docker images (multi-arch)
        id: docker-push
        uses: nais/docker-build-push@v0
        with:
          team: teammelosys
          tag: |
              type=raw,value=latest,priority=9001
              type=raw,value=${{ github.sha }},priority=9000
          platforms: linux/amd64,linux/arm64
          salsa: true

  deploy:
    runs-on: ubuntu-latest-8-cores
    needs: build
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pre-deploy
        uses: navikt/digihot-deploy/actions/pre-deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy q2
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/nais.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          VARS: nais/vars-q2.json
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
      - name: Deploy q1
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/nais.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          VARS: nais/vars-q1.json
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
      - name: Get commit message
        run: echo "COMMIT_MSG=$(git log --format=%s -n 1)" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: "melosys-web ${{ job.status == 'success' && 'ble deployet' || 'kunne ikke deployes' }} til q1 og q2"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ env.COMMIT_MSG }}
      - name: post-deploy
        uses: navikt/digihot-deploy/actions/post-deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: draft release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: ${{ env.APPLICATION }} ${{ env.VERSION_TAG }}
          body: ${{ env.CHANGE_LOG }}
          draft: true
          prerelease: false
