name: Deploy manuelt
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Miljø (q1, q2 eller prod)'
        required: true
        default: 'q2'

permissions:
  contents: write
  packages: write
  id-token: write

env:
  IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/teammelosys/melosys-web:${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check_docker_image_exists:
    name: Check if docker image exists in registry
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Login to NAIS registry
        uses: nais/login@v0
        with:
          team: teammelosys
      - name: Check if image exists
        id: check_image
        run: |
          if docker pull ${{ env.IMAGE }} >/dev/null 2>&1; then
            echo "Image eksisterer i registry"
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Image eksisterer ikke i registry"
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      exists: ${{ steps.check_image.outputs.image_exists }}

  build:
    runs-on: ubuntu-latest-8-cores
    needs: check_docker_image_exists
    if: needs.check_docker_image_exists.outputs.exists != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '22.11.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'pnpm'

      - name: install dependencies
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: pnpm install --frozen-lockfile

      - name: check formatting
        run: pnpm prettier:check
      - name: lint
        run: pnpm eslint
      - name: test
        run: pnpm test
        env:
          CI: false
      - name: build
        run: |
          BRANCH_NAME=$GITHUB_REF
          BUILD_NUMBER="$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)"
          pnpm build
      - name: Build and publish Docker image
        uses: nais/docker-build-push@v0
        with:
          team: teammelosys
          tag: ${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest-8-cores
    needs: [build, check_docker_image_exists]
    if: always() && (needs.build.result == 'success' || needs.build.result == 'skipped')
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: deploy to ${{github.event.inputs.environment}}
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{github.event.inputs.environment == 'prod' && 'prod-fss' || 'dev-fss' }}
          RESOURCE: nais/nais.yaml
          IMAGE: ${{ env.IMAGE }}
          VARS: nais/vars-${{github.event.inputs.environment}}.json
      - name: Get commit message
        run: echo "COMMIT_MSG=$(git log --format=%s -n 1)" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: "melosys-web ${{ job.status == 'success' && 'ble deployet' || 'kunne ikke deployes' }} til ${{github.event.inputs.environment}}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ env.COMMIT_MSG }}
