name: deploy-prod
on:
  release:
    types: [published]
permissions:
    contents: write
    packages: write
    id-token: write
jobs:
  deploy-prod:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/teammelosys/melosys-web:${{ github.sha }}
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Login to NAIS registry
        uses: nais/login@v0
        with:
          team: teammelosys
      - name: Verify image exists
        run: |
          docker pull ${{ env.IMAGE }}
          echo "✅ Image ${{ env.IMAGE }} eksisterer og kan hentes"
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: nais/nais.yaml
          IMAGE: ${{ env.IMAGE }}
          VARS: nais/vars-prod.json
      - name: post-production
        uses: navikt/digihot-deploy/actions/post-production@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get commit message
        run: echo "COMMIT_MSG=$(git log --format=%s -n 1)" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.4.0
        env:
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: "melosys-web ${{ job.status == 'success' && 'ble deployet' || 'kunne ikke deployes' }} til prod"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ env.COMMIT_MSG }}
