name: draft-release
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - master
permissions:
  contents: write
  packages: write
env:
  docker_image: docker.pkg.github.com/${{ github.repository }}/melosys-web:${{ github.sha }}
jobs:
  build:
    name: Build image for production and draft release
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
      - name: install dependencies
        env:
          # NPM krever tydeligvis en token for å hente pakker fra github packages
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm ci
      - name: check formatting
        run: npm run prettier:check
      - name: build css
        run: npm run build:css
      - name: lint
        run: npm run eslint
      - name: test
        run: npm run test
        env:
          CI: true
      - name: build
        run: |
          BRANCH_NAME=$GITHUB_REF
          BUILD_NUMBER="$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)"
          npm run build:prod
      - name: pre-deploy
        uses: navikt/digihot-deploy/actions/pre-deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${docker_image} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${docker_image}
      - name: get commit message
        run: | # Må hentes med et script fordi workflow_dispatch ikke har github.event.head_commit
          echo "COMMIT_MSG=$(git log --format=%s -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
      - name: post-deploy
        uses: navikt/digihot-deploy/actions/post-deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: draft release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: ${{ env.APPLICATION }} ${{ env.VERSION_TAG }}
          body: ${{ env.CHANGE_LOG }}
          draft: true
          prerelease: false
