name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest-8-cores

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '22.11.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'pnpm'

      - name: install dependencies
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: pnpm install --frozen-lockfile

      - name: check formatting
        run: pnpm prettier:check

      - name: lint
        run: pnpm eslint

      - name: test
        run: pnpm test
        env:
          CI: true

      - name: build
        run: |
          BRANCH_NAME=$GITHUB_REF
          BUILD_NUMBER="$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)"
          pnpm build

      - name: test container
        run: pnpm test:container
