name: Build

on: pull_request

jobs:
  check-file-length:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Check file length
        run: |
          exceeded_files=()
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
             echo "filechange"
            if [[ "$file" == src/**/*.js || "$file" == src/**/*.jsx || "$file" == src/**/*.ts || "$file" == src/**/*.tsx ]]; then
              if [ -f "$file" ]; then
                line_count=$(wc -l < "$file")
                if [ "$line_count" -gt 400 ]; then
                  exceeded_files+=("$file ($line_count lines)")
                fi
              fi
            fi
          done

          if [ ${#exceeded_files[@]} -ne 0 ]; then
            echo "❌ The following React files exceed 400 lines:"
            printf '%s\n' "${exceeded_files[@]}"
            exit 1
          else
            echo "✅ All React files are within the limit."
          fi
  build:
    runs-on: ubuntu-latest-8-cores

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '22.11.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'

      - name: install dependencies
        env:
          # NPM krever tydeligvis en token for å hente pakker fra github packages
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm ci

      - name: check formatting
        run: npm run prettier:check

      - name: build css
        run: npm run build:css

      - name: lint
        run: npm run eslint

      - name: test
        run: npm run test
        env:
          CI: true

      - name: build
        run: |
          BRANCH_NAME=$GITHUB_REF
          BUILD_NUMBER="$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)"
          npm run build
