name: Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.3.1'

      - name: npm install
        run: npm i

      - name: build css
        run: npm run build:css

      - name: lint
        run: npm run eslint

      - name: test
        run: npm run test:ci
        env:
          CI: true

      - name: build
        run: npm run build

      - name: Upload bundle
        uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: ./build

  deploy-t8:
    # if: github.ref == 'refs/heads/SPRINT-*'
    # if: github.ref == 'refs/heads/MELOSYS-3414_*'
    if: contains(github.ref, 'MELOSYS-3414')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download bundle
        uses: actions/download-artifact@v1
        with:
          name: bundle
          path: ./build

      - name: Create Docker tag
        env:
          NAME: melosys-web
        run: |
          echo "docker.pkg.github.com"/"$GITHUB_REPOSITORY"/"$NAME" > .docker_image
          echo "$(node -p "require('./package.json').version")-$(git rev-parse --short HEAD)" > .docker_tag

      - name: Build docker image
        run: docker build -t $(cat .docker_image):$(cat .docker_tag) .

      - name: Login to Github Package Registry
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}

      - name: Push Docker image
        run: docker push $(cat .docker_image):$(cat .docker_tag)

      - name: Deploy til t8
        uses: navikt/deployment-cli/action@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWAIT_SECONDS: 0
        with:
          cluster: dev-fss
          team: teammelosys
          resources: nais/t8/app.yaml
